name: calculator
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  math_expressions: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0  

flutter_icons:
  image_path: "assets/calculator_icon.jpg"
  android: true
  ios: true    


flutter:

  uses-material-design: true